const GEN_BOARD = 'GEN_BOARD';
const SELECT_CELL = 'SELECT_CELL';
const ENTER_NUM = 'ENTER_NUM';
const SET_NOTE_MODE = 'SET_NOTE_MODE';
const START_GEN_BOARD = 'START_GEN_BOARD';

export {GEN_BOARD, SELECT_CELL, ENTER_NUM, SET_NOTE_MODE, START_GEN_BOARD};
